/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package act4;

import java.awt.Component;
import java.util.*;

/**
 *
 * @author jero
 */
public class Menu extends javax.swing.JFrame {
    
    public static TreeSet<Productos> listaProductos=new TreeSet<>();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        botonProductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        botonPorRubro = new javax.swing.JMenuItem();
        botonPorNombre = new javax.swing.JMenuItem();
        botonPorPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jMenu1.setForeground(java.awt.Color.black);
        jMenu1.setText("Administracion");

        botonProductos.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        botonProductos.setForeground(java.awt.Color.black);
        botonProductos.setText("Productos");
        botonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProductosActionPerformed(evt);
            }
        });
        jMenu1.add(botonProductos);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(java.awt.Color.black);
        jMenu2.setText("Consultas");

        botonPorRubro.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        botonPorRubro.setForeground(java.awt.Color.black);
        botonPorRubro.setText("Por Rubro");
        botonPorRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPorRubroActionPerformed(evt);
            }
        });
        jMenu2.add(botonPorRubro);

        botonPorNombre.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        botonPorNombre.setForeground(java.awt.Color.black);
        botonPorNombre.setText("Por Nombre");
        botonPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPorNombreActionPerformed(evt);
            }
        });
        jMenu2.add(botonPorNombre);

        botonPorPrecio.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        botonPorPrecio.setForeground(java.awt.Color.black);
        botonPorPrecio.setText("Por Precio");
        botonPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPorPrecioActionPerformed(evt);
            }
        });
        jMenu2.add(botonPorPrecio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductosActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();
        escritorio.repaint();
        GestionProductos gp=new GestionProductos();
        iFrameCentrado(gp);
        escritorio.moveToFront(gp);
    }//GEN-LAST:event_botonProductosActionPerformed

    private void botonPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPorRubroActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        PorRubro pr=new PorRubro();
        iFrameCentrado(pr);
        escritorio.moveToFront(pr);
    }//GEN-LAST:event_botonPorRubroActionPerformed

    private void botonPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPorNombreActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        PorNombre pn=new PorNombre();
        iFrameCentrado(pn);
        escritorio.moveToFront(pn);
    }//GEN-LAST:event_botonPorNombreActionPerformed

    private void botonPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPorPrecioActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        PorPrecio pp=new PorPrecio();
        iFrameCentrado(pp);
        escritorio.moveToFront(pp);
    }//GEN-LAST:event_botonPorPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem botonPorNombre;
    private javax.swing.JMenuItem botonPorPrecio;
    private javax.swing.JMenuItem botonPorRubro;
    private javax.swing.JMenuItem botonProductos;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    private void cargarProductos(){
        listaProductos.add(new Productos(1,"Carne",1200,10, Categorias.COMESTIBLES));
        listaProductos.add(new Productos(2,"Lavandina",430,10, Categorias.LIMPIEZA));
        listaProductos.add(new Productos(3,"Perfumina",480,10, Categorias.PERFUMERIA));
        listaProductos.add(new Productos(4,"Pringles",640,10, Categorias.COMESTIBLES));
    }
    
    public void iFrameCentrado(Component frameCentrado) {        
    escritorio.add(frameCentrado);
    frameCentrado.setLocation((escritorio.getWidth()-frameCentrado.getWidth())/2, (escritorio.getHeight()-frameCentrado.getHeight())/2);
    frameCentrado.setVisible(true);
}


}
