/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package act4;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jero
 */
public class PorPrecio extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo=new DefaultTableModel();

    /**
     * Creates new form PorPrecio
     */
    public PorPrecio() {
        initComponents();
        armarCabecera();
        setCero();
        mostrarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textMenorPrecio = new javax.swing.JTextField();
        textMayorPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPrecio = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Listado por precio");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Entre $");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("y");

        textMenorPrecio.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        textMenorPrecio.setForeground(java.awt.Color.black);
        textMenorPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textMenorPrecioKeyReleased(evt);
            }
        });

        textMayorPrecio.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        textMayorPrecio.setForeground(java.awt.Color.black);
        textMayorPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textMayorPrecioKeyReleased(evt);
            }
        });

        tablaPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPrecio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMenorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textMayorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textMenorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textMayorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMayorPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMayorPrecioKeyReleased
        // TODO add your handling code here:
        borrarFilas();
        try{
            for(Productos prod:Menu.listaProductos){
            int menor = Integer.parseInt(textMenorPrecio.getText());
            int mayor = Integer.parseInt(textMayorPrecio.getText());
            if(prod.getPrecio()>menor && prod.getPrecio()<mayor){
                modelo.addRow(new Object[]{
                    prod.getCodigo(),
                    prod.getDescripcion(),
                    prod.getPrecio(),
                    prod.getStock()
                    });
                }
            }
        }catch(NumberFormatException e){
            if(textMenorPrecio.getText()==null){
                textMenorPrecio.setText("0");
            }else if(textMayorPrecio.getText()==null){
                textMayorPrecio.setText("0");
            }
        }
        
    }//GEN-LAST:event_textMayorPrecioKeyReleased

    private void textMenorPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMenorPrecioKeyReleased
        // TODO add your handling code here:
        borrarFilas();
        try{
            int menor = Integer.parseInt(textMenorPrecio.getText());
            int mayor = Integer.parseInt(textMayorPrecio.getText());
            for(Productos prod:Menu.listaProductos){
                 if(prod.getPrecio()>menor && prod.getPrecio()<mayor){
                    modelo.addRow(new Object[]{
                        prod.getCodigo(),
                        prod.getDescripcion(),
                        prod.getPrecio(),
                        prod.getStock()
                     });
                }
            }
        }catch(NumberFormatException e){
            if(textMenorPrecio.getText()==null){
                textMenorPrecio.setText("0");
            }else if(textMayorPrecio.getText()==null){
                textMayorPrecio.setText("0");
            }
        }
        
    }//GEN-LAST:event_textMenorPrecioKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPrecio;
    private javax.swing.JTextField textMayorPrecio;
    private javax.swing.JTextField textMenorPrecio;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        tablaPrecio.setModel(modelo);
    }
    
    private void borrarFilas(){
        int f=tablaPrecio.getRowCount()-1;
        for(;f>=0;f--){
            modelo.removeRow(f);
        }
    }
    
    private void setCero(){
        textMenorPrecio.setText("0");
        textMayorPrecio.setText("0");
    }
    
    private void mostrarProductos(){
        for(Productos aggprod:Menu.listaProductos){
            modelo.addRow(new Object[]{
                aggprod.getCodigo(),
                aggprod.getDescripcion(),
                aggprod.getPrecio(),
                aggprod.getStock()
            });
        }
    }

}
