/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package act4;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jero
 */
public class PorRubro extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo=new DefaultTableModel();
    private DefaultComboBoxModel modelocb=new DefaultComboBoxModel();

    /**
     * Creates new form PorRubro
     */
    public PorRubro() {
        initComponents();
        armarCabecera();
        armarCategorias();
        mostrarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listaRubroPR = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPorRubro = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Listado de productos por rubro");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Rubro:");

        listaRubroPR.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        listaRubroPR.setForeground(java.awt.Color.black);
        listaRubroPR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaRubroPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaRubroPRActionPerformed(evt);
            }
        });

        tablaPorRubro.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        tablaPorRubro.setForeground(java.awt.Color.black);
        tablaPorRubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPorRubro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(listaRubroPR, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(listaRubroPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaRubroPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaRubroPRActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        ordenarProductos();
    }//GEN-LAST:event_listaRubroPRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listaRubroPR;
    private javax.swing.JTable tablaPorRubro;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        tablaPorRubro.setModel(modelo);
    }
    
    private void armarCategorias(){
        modelocb.addElement("Seleccionar...");
        modelocb.addElement("Comestibles");
        modelocb.addElement("Limpieza");
        modelocb.addElement("Perfumeria");
        listaRubroPR.setModel(modelocb);
    }
    
    private void mostrarProductos(){
        for(Productos aggprod:Menu.listaProductos){
            modelo.addRow(new Object[]{
                aggprod.getCodigo(),
                aggprod.getDescripcion(),
                aggprod.getPrecio(),
                aggprod.getStock()
            });
        }
    }
    
    private void borrarFilas(){
        int f=tablaPorRubro.getRowCount()-1;
        for(;f>=0;f--){
            modelo.removeRow(f);
        }
    }
    
    private void ordenarProductos(){
        for(Productos mostprod:Menu.listaProductos){
            if(mostprod.getRubro().toString().equalsIgnoreCase((String)listaRubroPR.getSelectedItem())) {
                modelo.addRow(new Object[]{
                mostprod.getCodigo(),
                mostprod.getDescripcion(),
                mostprod.getPrecio(),
                mostprod.getStock()
                });
            }else if(listaRubroPR.getSelectedItem()=="Seleccionar..."){
                borrarFilas();
                mostrarProductos();
            }
        }
    }


}
